### PR TITLE
Fix issues with recursive usage

### LINKED ISSUE #34: Recursive calls to import::from() do not work
Calling `import::*()` recursively (that is, importing functions from a module that itself imports functions from another module) does not work if _unless_ the inner import statement uses `import::here()`. Specifically, it works if the inner import statement imports into `{environment()}`, which is what happens when using `import::here()`

This is the root cause of several other issues that have been marked as fixed-in-master. 

It would be preferable if all discussions about this issue take place here, rather than in other issues that are mostly a symptom of this issue.

### PR DESCRIPTION
**Pull request by torfason**
This PR fixes #34 and #35.

### CODE REVIEW

**Comment by torfason** [comment]
I guess the checks don't run because they are not specified `on: [push, pull_request]` for this branch. Probably better to merge PR #30 into master first, and then into this PR, rather than adding again here and conflicting. I can do that after review.

File: R/detect_bad_recursion.R [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+#' A bad recursion is a recursion in which the
+#'
+#' @param stack_trace A list object containing the value of a \code{.traceback()} call
+#' @return logical indicating whether a bad recursion call was detected
+#'
+#' @noRd
+detect_bad_recursion <- function(stack_trace) {
+
+  # Extract all lines correxponding to calls to import::*
+  x <- grep("^import::",unlist(stack_trace), value=TRUE)
```
Comment (smbache) [inline R/detect_bad_recursion.R:20]:
```suggestion
  x <- grep("^import::", unlist(stack_trace), value = TRUE)
```

File: R/detect_bad_recursion.R [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+#' imported should only be done with import::here(). Never with
+#' import::from() or import::into()
+#'
+#' A bad recursion is a recursion in which the
+#'
+#' @param stack_trace A list object containing the value of a \code{.traceback()} call
+#' @return logical indicating whether a bad recursion call was detected
+#'
+#' @noRd
+detect_bad_recursion <- function(stack_trace) {
```
Comment (smbache) [inline R/detect_bad_recursion.R:17]: Will the [redirects/dispatch to `from`](https://github.com/smbache/import/blob/master/R/here.R#L18) cause problems?

File: R/detect_bad_recursion.R [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+  # a recursive call. That is OK, as long as the last call originates+
+  # in a call to import here (i.e. the second element in the vector
+  # starts with import:::?here)
+  if ( length(grep("^import:::?from", x, value=TRUE)) > 1 ) {
+    if ( !grepl("^import:::?here", x[2])) {
+      # Ouch, we have detected a bad recursion
+      return(TRUE)
+    }
+  }
+  return(FALSE)
```
Comment (smbache) [inline R/detect_bad_recursion.R:32]:
```suggestion
  length(grep("^import:::?from", x)) > 1 && grepl("^import:::?here", x[2]))
```
Is `x[2]` guaranteed to exist? I suppose it will always be a scalar if so. Otherswise
```R
  length(grep("^import:::?from", x)) > 1 && length(x) > 1  && grepl("^import:::?here", x[2]))
```

File: R/here.R [hunk 4]
```diff
@@ -1,6 +1,6 @@
 #' @rdname importfunctions
 #' @export
-here <- function(..., .from, .library = .libPaths()[1L],
+here <- function(.from, ..., .library = .libPaths()[1L],
```
Comment (smbache) [inline R/here.R:3]: is this a breaking change? The idea was that it reads funny if you without specifying ".from"...

File: tests/test_import/module_recursive_package_here.R [hunk 5]
```diff
@@ -0,0 +1,7 @@
+# Import utility function or package using import::here() is the recommended usage
+import::here(knitr, normal_print)
```
Comment (smbache) [inline tests/test_import/module_recursive_package_here.R:2]: I wonder, generally, if we should rely on "suggest" packages, other than testthat, for tests?

File: R/detect_bad_recursion.R (hunk 2 above)
Comment (torfason) [reply R/detect_bad_recursion.R:17]: I think not, that is what lines 27-29 are intended to do. If we find ourselves in "good recursion" (the inner call was made through `import::here()`, then the trace (after grepping only for lines starting with `import`:

```
[1] "import::from(.from = module_recursive_inner.R, to_title, .into = {"
[2] "import::here(module_recursive_inner.R, to_title)"                  
[3] "import::from(module_recursive_outer_here.R, print_title_text)"  
```

Basically, an arbitrary number of  import statements, but the last two (the only ones we examine at this point, because any outer statements were presumably either legal or have been fixed already) should be first a `from()` (because that's the only place we perform the test, and then a `here()` (where the dispatch originated). 

Not claiming this is elegant, but logically it seems to me like it should work, and the tests also seem to bear that out.

Comment (smbache) [reply R/detect_bad_recursion.R:17]: ✅

File: R/here.R (hunk 4 above)
Comment (smbache) [reply R/here.R:3]: Ok, sounds good.

In theory, a call to `import::from` with the right environment set should also work, but I guess it's not too important. Or at least we can see if it becomes important, and not worry about it now.

File: tests/test_import/module_recursive_package_here.R (hunk 5 above)
Comment (torfason) [reply tests/test_import/module_recursive_package_here.R:2]: I believe that is what the guidelines (from documentation on testthat, I think) suggest. And the CRAN servers ensure that suggests packages are installed before running the tests.

Given the purpose of the package, it's impossible to perform tests from packages without relying on other packages. But an end user does not really need any specific packages, and moving the dependency to Import would force the end users to install them along with import.

File: R/here.R (hunk 4 above)
Comment (torfason) [reply R/here.R:3]: Agreed, but that would be way harder (and I worry, less robust) to check for. I also think that for the end user, telling them that any inner import statement should be a `here()` statement is simpler messaging than guidelines on which environments should work.

File: tests/test_import/module_recursive_package_here.R (hunk 5 above)
Comment (smbache) [reply tests/test_import/module_recursive_package_here.R:2]: Not too big a deal - either way. But one could use packages that are shipped with R, eg utils, tools, methods, ...

Comment (torfason) [reply tests/test_import/module_recursive_package_here.R:2]: I see, yes, that's probably true, but regardless, I'd vote to keep it as is for now :-)

File: R/here.R (hunk 4 above)
Comment (smbache) [reply R/here.R:3]: ✅

File: tests/test_import/module_recursive_package_here.R (hunk 5 above)
Comment (smbache) [reply tests/test_import/module_recursive_package_here.R:2]: ✅
